Competitions map
Competitive-Cyber-Clubs/competitivecyberclubs.github.io pull request #23
Opened 2022-03-03 01:53 UTC by AnthonyCamper

2022-03-03 01:53 UTC, AnthonyCamper commented
Looks good to me

2022-03-03 02:23 UTC, Cyb3r-Jak3 reviewed
I noticed that there is a random pop-up on the page. This should be removed

![original](https://user-images.githubusercontent.com/13918954/156484068-42ac2221-d032-46ae-a8a7-12015e1a9ef3.png)

2022-03-03 02:23 UTC, Cyb3r-Jak3 commented on public/json/clubs.json
> +        "isctf":false},
Can you remove this fake school.

2022-03-03 02:23 UTC, Cyb3r-Jak3 requested changes
Please look at comments

2022-03-04 02:04 UTC, AnthonyCamper commented
> I noticed that there is a random pop-up on the page. This should be removed
> 
> ![original](https://user-images.githubusercontent.com/13918954/156484068-42ac2221-d032-46ae-a8a7-12015e1a9ef3.png)

Removed files

2022-03-04 02:45 UTC, Cyb3r-Jak3 approved these changes
LGTM! Nice work

2022-03-04 02:47 UTC, merged